### ISSUE TITLE
Thank you for this... here is the corrected code

### ISSUE THREAD

**Issue by bobbyconnolly** [jmlweb/isMounted#1]
```
import { useRef, useEffect } from 'react';

const useIsMounted = () => {
    const isMounted = useRef(true);
    useEffect(
        () => () => {
            isMounted.current = false;
        },
        [],
    );
    return isMounted;
};

export default useIsMounted;
```

then, in your component you check 
```
 const isMounted = useIsMounted();

 if (isMounted.current) {
  // setSomethingSafely('bla')
 }
```
a gotcha moment for me was that I tried to return isMounted.current (which was a nono because useIsMounted is a hook and must return the useRef!!!)

The above code works great for me.

Thanks again for your tip!

**Comment by jmlweb** [comment]
@bobbyconnolly Thanks for your tip! It has been merged into version 0.0.2 https://github.com/jmlweb/isMounted/commit/b58ac3196bb9a684642737756113e56150148493
